defaults:
  - environment: grogu
  - hydra: default
  - data@trainsets: hoi4d # ho3d_crop_cam
  - data@testsets: hoi4d # ho3d_crop_cam
  - model: glide
  - mode: geom
ndim: 
ndim_cond: 0
zfar: 0
bin: 0.5

cat_level: True
uncond_image: false
# mode:
#   mask: 1
#   normal: 1
#   depth: 1
#   uv: False
#   cond: 1

worker: ddpm2d.models.glide_base
train_prob: 
  - 1
  - 1

expname: dev/tmp
output: ${environment.output}
checkpoints_dir: ${output}/${expname}
outputs_dir: ${checkpoints_dir}/log
exp_dir: ${checkpoints_dir}
project_name: 'vhoiddpm_'
test_name: default_test

ho3d:
  split: train_seg
hoi4d:
  split: 

test_batch_size: 8

resume_ckpt: ${model.resume_ckpt}
resume_train_from: ${exp_dir}/checkpoints/last.ckpt
ckpt: ${resume_train_from}
use_fp16: False


eval: False
logging: wandb
batch_size: 8
learning_rate: 1e-4
adam_weight_decay: 0.01
side_x: 64
side_y: ${side_x}

use_captions: True
uncond_p: 0.2
use_flip: False

device: cuda
log_frequency: 5000
print_frequency: 100
save_frequency: 20000
save_topk: 1
sanity_step: 1
max_steps: 500000

enable_inpaint: False
enable_upsample: False

activation_checkpointing: False

test_guidance_scale: 4
sample_respacing: '100'
gradient_accumualation_steps: 1
use_webdataset: False
seed: 123
upsample_factor: 4

cudnn_benchmark: True

beta_schdl: 'squaredcos_cap_v2'