resume: True


world_size: 1
rank: 0
dist_url: tcp://localhost:10001
dist_backend: nccl
port: 10001
node: localhost


multiprocessing_distributed: True
distributed: True
seed:
gpu:
ngpu: 1
workers: 80
mem_gb: 256

slurm: True
slurm_partition: devlab
slurm_timeout: 2880
nodelist: ""
exclude_nodes: ""

