# wipe out the existing folder, no slurm
resume: False

workers: 80

world_size: 1
rank: 0
dist_url: tcp://localhost:10001
dist_backend: nccl
port: 10001
node: localhost


multiprocessing_distributed: False
distributed: True
seed:
gpu:
ngpu: 2
mem_gb: 256

slurm: False
slurm_partition: none
slurm_timeout: 2880
nodelist: ""
exclude_nodes: ""

