arch: models.deepsdf.deepsdf.AutoDecoder
dec_arch: models.deepsdf.deepsdf.ArtCondDecoder
NetworkSpecs : 
  latent_size: ${deepsdf.TrainSpecs.CodeLength}
  dims : 
    - 512 
    - 512 
    - 512 
    - 512 
    - 512 
    - 512 
    - 512 
    - 512
  dropout : 
    - 0 
    - 1 
    - 2 
    - 3 
    - 4 
    - 5 
    - 6 
    - 7
  dropout_prob : 0.2
  norm_layers : 
    - 0 
    - 1 
    - 2 
    - 3 
    - 4 
    - 5 
    - 6 
    - 7
  latent_in : 
    - 4
  xyz_in_all : false
  use_tanh : false
  latent_dropout : false
  weight_norm : true
  xyz_dim: 51


TrainSpecs:
  CodeLength : 256
  NumEpochs : 2001
  SnapshotFrequency : 1000
  LearningRateSchedule :
    # - lr:
    Type : Step
    Initial : 0.0005
    Interval : 500
    Factor : 0.5
  
    # - lr:
    #   Type : Step
    #   Initial : 0.001
    #   Interval : 500
    #   Factor : 0.5
  SamplesPerScene : ${point_reso}
  ScenesPerBatch : ${batch_size}
  DataLoaderThreads : 16
  ClampingDistance : 0.1
  CodeRegularization : true
  CodeRegularizationLambda : 1e-4
  CodeBound : 1.0
  GradientClipNorm: 0.
  enforce_minmax: True