bs: 8
T: 100
common_dir: /glusterfs/yufeiy2/vhoi/output_ddpm/
ckpt: art/art/ckpt/model-00020000.pt
split: test_full
q_sample: True
data_dir: /glusterfs/yufeiy2/fair/data/obman/
idx: 2


hydra:
  sweep:
    dir: ${common_dir}/tmp_hydra_cache
    subdir: ID${hydra.job.id} 
  run:
    dir: ${common_dir}/tmp_hydra_cache
