frame: camera
mode: geom # geom / semantics
amodal: amodal  # mixed / amodal / occlusion
t_std: 0.1 # tranlsation standard deviate

diff_dir: single_mode2
diff_index: CondGeomGlide_cond_all_linear_catTrue_cfgFalse
diff_name: ${novel_view.diff_dir}/${novel_view.diff_index}
diffuse_ckpt: '${environment.output}/${novel_view.diff_name}/checkpoints/last.ckpt'

dummy_param: 0

sd_para:
  min_step: 0.02
  max_step: 0.98
  to_step: 0.5
  anneal_noise: exp
  guidance_scale: 4
  prediction_respacing: 100
  prompt: 'a semantic segmentation of a hand grasping an object'

loss:
  w_spatial: False # spatially adjusted weight TODOs
  w_mask: 1. 
  w_normal: 1. 
  w_depth: 1. 
  w_schdl: bell
