frame: camera
mode: geom # geom / semantics
amodal: amodal  # mixed / amodal / occlusion
t_std: 0.1 # tranlsation standard deviate

diff_name: single_mode/cond_all_linear_0_0.5
diffuse_ckpt: '/home/yufeiy2/scratch/result/vhoi/${novel_view.diff_name}/checkpoints/last.ckpt'

dummy_param: 0

sd_para:
  min_step: 0.02
  max_step: 0.98
  guidance_scale: 4
  prediction_respacing: 100
  prompt: 'a semantic segmentation of a hand grasping an object'

loss:
  w_spatial: False # spatially adjusted weight TODOs
  w_mask: 1. 
  w_normal: 1. 
  w_depth: 1. 
  w_schdl: bell
