log_root_dir: ${output}
exp_dir: ${training.log_root_dir}/${expname}
beta_init: 0.1
speed_factor: 10.0

render_full_frame: True

# lr: 5.0e-4
lr: 
  model: 5.0e-4
  pose: 1.0e-3
  focal: 1.0e-3
  oTh: 1.0e-3
  text: 1.0e-3

w_eikonal: 0.1
w_mask: 10. 
w_depth: 0.   # ordinal depth hurts!!
w_rgb: 1. 
w_flow: 0. 
w_sdf: 0. 
w_t_hand: 100. 
w_contour: 10. 
w_contact: 0. 
w_diffuse: 1.   # diffusion model
backward: 'once'
clip: 100

fg: 1
occ_mask: label  # union | indp | label? 
label_prob: 1


num_iters: 2000 # 50000

# lr decay
scheduler:
  type: exponential_step
  min_factor: 0.1

ckpt_file: null # will be read by python as None
ckpt_ignore_keys: []     # only change if you want to drop certain keys in the saved checkpionts.
ckpt_only_use_keys: null # only change if you want to only use certain keys in the saved checkpionts.

monitoring: ${logging.mode}

i_save: 200 # 1000       # unit: seconds
i_backup: 50000   # unit: itertation steps

i_val: 200 # 1000
i_val_mesh: 200 # 1000

print_freq: 11
