module: ddpm2d.models.glide
model:  Glide

grad_clip: 0. 
disable_transformer: False
freeze_transformer: True
freeze_diffusion: False
activation_checkpointing: False

resume_ckpt: ${environment.remote_str}/pretrain/glide/base.pt
