defaults:
  - environment: yoda
  - logging: wandb
  - hydra: default
  - deepsdf: occ

worker: 'ihoi.blind_prior'
output: "/glusterfs/yufeiy2/vhoi/output_ihoi/"
exp_dir: ${output}/${expname}
expname: dev/tmp


ddp: ${environment.multiprocessing_distributed} # deprecated

resume_dir:         # single GPU / DP / DDP; run on all available GPUs; 
# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1        # single GPU / DP / DDP; run on all available GPUs; 

mode: cond
resample: True  
z_dim: 256
enc: 
  mode: geo
  params:
    k: 20
    emb_dims: 256
    dropout: 0.2

loss:
  kl: 1e-2

data:
  mode: occ  # occ / sdf
  train: [mow, obman]
  val: [mow, obman]
  test: [mow, obman]

  jitter_xyz: 0.05
  jitter_trans: 0.05
  jitter_rot: 0.1
  jitter_scale: 0.1
point_reso: 4096


n_save_freq: 5000
n_eval_freq: 2500
max_step: 100000

training:
  n_print: 100
  ckpt_file: None
  lr: 1.e-4
  batch_size: 8


test:
  batch_size: 8
