defaults:
  - environment: yoda
  - logging: wandb
  - hydra: default
  - unet_config: ddim_cond

worker: 'ddpm.main'
output: "/glusterfs/yufeiy2/vhoi/output_ddpm/"
exp_dir: ${output}/${expname}
expname: dev/tmp


ddp: ${environment.multiprocessing_distributed} # deprecated

resume_dir:         # single GPU / DP / DDP; run on all available GPUs; 
# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1        # single GPU / DP / DDP; run on all available GPUs; 


data_dir: /glusterfs/yufeiy2/fair/data/obman/

point_reso: 32
batch_size: 16

time: 
  total: 1000
  start: 1000

n_save_freq: 2500
n_eval_freq: 2500
special_ckpt: [10, 1000, 2000, 3000, 5000, 7500, 10000]

# unet_config:
#   target: ddpm.openai.UNetModel
#   params:
#     image_size: 32
#     in_channels: 1
#     out_channels: 1
#     model_channels: 64
#     attention_resolutions:
#     - 16
#     - 8
#     num_res_blocks: 2
#     channel_mult:
#     - 1
#     - 2
#     - 2
#     - 4
#     num_head_channels: 32
#     dims: 3
#     context_dim: 135
#     use_spatial_transformer: True

training:
  ckpt_file: None