defaults:
  - environment: yoda
  - logging: wandb
  - hydra: default
  - unet_config: ddim_uncond

worker: 'ddpm.main'
output: "/glusterfs/yufeiy2/vhoi/output_ddpm/"
exp_dir: ${output}/${expname}
expname: dev/tmp


ddp: ${environment.multiprocessing_distributed} # deprecated

resume_dir:         # single GPU / DP / DDP; run on all available GPUs; 
# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1        # single GPU / DP / DDP; run on all available GPUs; 


train_split: 'obman'
test_split: 'obman'
data_dir: '/glusterfs/yufeiy2/fair/mesh_sdf/' 
data_mode: 'osdf'

point_reso: 32
batch_size: 16

lr: 1e-4

cf_prob: 0.

time: 
  total: 1000
  start: 1000

n_save_freq: 5000
n_eval_freq: 2500
special_ckpt: [10, 1000, 2000, 3000, 5000, 7500, 10000]

training:
  ckpt_file: None