defaults:
  - environment: default
  - logging: default
  - hydra: default
  - data: ho3d
  - camera: gt
  - oTh: gt


output: "/checkpoint/yufeiy2/vhoi_out/neurecon_out"
expname: dev/tmp


ddp: ${environment.multiprocessing_distributed} # deprecated
resume_dir: 

# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1        # single GPU / DP / DDP; run on all available GPUs; 

test_train: 0


model:
  framework: VolSDFHOI
  obj_bounding_radius: 3.0  # scene sphere, as in the VolSDF paper
  
  outside_scene: "builtin"  # [builtin, nerf++]
  max_upsample_iter: 6      # up sample iteratioms, as in the VolSDF paper

  W_geometry_feature: 256
  use_siren: False
  perturb: True
  white_bkgd: False
  surface:
    radius_init: 1.0        # as in VolSDF supp B.3, unit sphere
    D: 8
    W: 256
    skips: [4]
    embed_multires: 6
    use_siren: False
    geometric_init: True

  radiance:
    use_siren: False
    use_view_dirs: True
    D: 4
    W: 256
    skips: []
    embed_multires: -1
    embed_multires_view: -1

  joint_frame: 'object_norm'  # object_norm / hand_norm

blend_train:
  method: 'soft'
  sigma: 1e-4
  gamma: 1e-4
  background_color: [1.0, 1.0, 1.0]
  
# camera:
#   mode: 'gt'  # gt, ft, net, para
#   hypothesis: 1
#   learn_R: 1
#   learn_t: 1
#   init_dist: 2
#   learn_f: 1
#   learn_pp: 1
#   fx_only: 1
#   order_f: 2
#   init_f: 2.

# oTh:
#   mode: 'gt'
#   learn_R: False
#   learn_t: False
#   learn_base_s: False
#   learn_base_R: False
#   learn_base_t: False

training:
  exp_dir: ${training.log_root_dir}/${expname}
  
  beta_init: 0.1
  speed_factor: 10.0

  # lr: 5.0e-4
  lr: 
    model: 5.0e-4
    pose: 1.0e-3
    focal: 1.0e-3
    oTh: 1.0e-3

  w_eikonal: 0.1
  w_mask: 1. 
  w_flow: 0. 
  w_sdf: 0. 
  fg: 1
  occ_mask: union  # union or indp

  log_root_dir: "/checkpoint/yufeiy2/vhoi_out/neurecon_out"

  num_iters: 50000

  # lr decay
  scheduler:
    type: exponential_step
    min_factor: 0.1

  ckpt_file: null # will be read by python as None
  ckpt_ignore_keys: []     # only change if you want to drop certain keys in the saved checkpionts.
  ckpt_only_use_keys: null # only change if you want to only use certain keys in the saved checkpionts.

  monitoring: wandb

  i_save: 1000       # unit: seconds
  i_backup: 50000   # unit: itertation steps

  i_val: 1000
  i_val_mesh: 1000

  print_freq: 10
