defaults:
  - environment: grogu_judy
  - logging: wandb
  - hydra: default
  - data: 100doh
  - camera: delta
  - oTh: learn
  - training: default
  - novel_view: semantic
  - model: small

worker: 'train'
output: ${environment.output}
expname: dev/tmp
exp_dir: ${output}/${expname}

hA:
  mode: 'learn'  # gt / learn

ddp: ${environment.multiprocessing_distributed} # deprecated
resume_dir: 

# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: [0]        # single GPU / DP / DDP; run on all available GPUs; 

test_train: 0



hand_text:
  size: 6

blend_train:
  method: vol
  sigma: 1e-4
  gamma: 1e-4
  background_color: [1.0, 1.0, 1.0]
  
