expname: volsdf_65

# device_ids: [0]     # single gpu           ; run on specified GPU
# device_ids: [1, 0]  # DP                   ; run on specified GPU
device_ids: -1        # single GPU / DP / DDP; run on all available GPUs; 

test_train: 0

data:
  type: HOI
  batch_size: 1       # one batch, one image
  data_dir: /checkpoint/yufeiy2/vhoi_out/syn_data/00006755
  downscale: 1        # downscale image for training
  scale_radius: 3.0   # scale the dataset's all camera to be within this radius
  pin_memory: True
  volume_size: 6.0

  near: 0.0
  far: 6.0  # NOTE: in volSDF，far = 2r=2*3=6.0

  N_rays: 1024        # N_rays for training
  val_rayschunk: 256 # N_rays for validation
  val_downscale: 4    # downscale image for validation

model:
  framework: VolSDFHOI
  obj_bounding_radius: 3.0  # scene sphere, as in the VolSDF paper
  
  outside_scene: "builtin"  # [builtin, nerf++]
  max_upsample_iter: 6      # up sample iteratioms, as in the VolSDF paper

  W_geometry_feature: 256

  surface:
    radius_init: 1.0        # as in VolSDF supp B.3, unit sphere
    D: 8
    skips: [4]
    embed_multires: 6

  radiance:
    D: 4
    skips: []
    embed_multires: -1
    embed_multires_view: -1
  joint_frame: 'object_norm'  # object_norm / hand_norm

camera:
  mode: 'gt'  # gt, ft, net, para
  hypothesis: 1
  learn_R: 1
  learn_t: 1
  init_dist: 2
  learn_f: 1
  learn_pp: 1
  fx_only: 1
  order_f: 2
  init_f: 2.

oTh:
  mode: 'gt'
  learn_R: False
  learn_t: False
  learn_base_s: False
  learn_base_R: False
  learn_base_t: False

training:
  speed_factor: 10.0

  # lr: 5.0e-4
  lr: 
    model: 5.0e-4
    pose: 1.0e-3
    focal: 1.0e-3
    oTh: 1.0e-3

  w_eikonal: 0.1
  w_mask: 1. 
  w_flow: 0. 
  w_sdf: 0. 
  fg: 1
  occ_mask: union  # union or indp

  log_root_dir: "../output/neurecon_out/"

  num_iters: 50000

  # lr decay
  scheduler:
    type: exponential_step
    min_factor: 0.1

  ckpt_file: null # will be read by python as None
  ckpt_ignore_keys: []     # only change if you want to drop certain keys in the saved checkpionts.
  ckpt_only_use_keys: null # only change if you want to only use certain keys in the saved checkpionts.

  monitoring: wandb

  i_save: 1000       # unit: seconds
  i_backup: 50000   # unit: itertation steps

  i_val: 1000
  i_val_mesh: 1000

  print_freq: 10
