defaults:
  - submitit_slurm

timeout_min: 120
partition: shubham,abhinav,abhinavlong,shubhamlong,all
gpus_per_node: 1
cpus_per_task: 16
mem_gb: 60
nodes: 1
constraint: A5000|rtx6000|rtx2080ti
max_num_timeout: 100

# # from senthil
# run:
#   dir: ${exp_dir}/outputs
# sweep:
#   dir: ${exp_dir}/outputs
#   subdir: ID${hydra.job.id} 
submitit_folder: ${exp_dir}/submitit_train_logs/
name: ${expname}


exclude: grogu-1-9,grogu-1-24