target: ddpm.openai.UNetModel
mode: artattn
art_para:
  pe_dim: 10
  reso: ${unet_config.params.image_size}
params:
  image_size: 32
  in_channels: 1 # 1 + (3*16) * 10?
  out_channels: 1
  model_channels: 64
  use_scale_shift_norm: True
  attention_resolutions:
  - 16
  - 8
  num_res_blocks: 2
  channel_mult:
  - 1
  - 2
  - 4
  num_head_channels: 32
  dims: 3
  context_dim: 30 # 3 * 10
  continuous_emb: null
  use_spatial_transformer: False

  use_res_attn: True
  use_coord: True
  pe_dim: 10
  pe_inp: True