target: ddpm.openai.UNetModel
params:
  image_size: 32
  in_channels: 1
  out_channels: 1
  model_channels: 64
  attention_resolutions:
  - 16
  - 8
  num_res_blocks: 2
  channel_mult:
  - 1
  - 2
  - 2
  - 4
  num_head_channels: 32
  dims: 3
  context_dim: 
  use_spatial_transformer: False