defaults:
  - submitit_slurm

signal_delay_s: 120
timeout_min: 360
partition: shubham,abhinav,abhinavlong,shubhamlong
gpus_per_node: 1
cpus_per_task: 16
mem_gb: 60
nodes: 1
# constraint: A5000|rtx6000|rtx2080ti
max_num_timeout: 100


submitit_folder: ${exp_dir}/submitit_train_logs/
name: ${expname}


exclude: grogu-1-9,grogu-1-24,grogu-1-34